### ISSUE TITLE
Downloading cfg file

### ISSUE THREAD

**Issue by madaxel** [schams-net/nagios_check_typo3#1]
Hi @schams-net ,
the link to the downloads section for the cfg (https://schams.net/nagios) file is not working anymore.

Can you point me to the right URL?

**Comment by schams-net** [comment]
Hi @madaxel - try <https://schams.net/nagios/downloads/check-typo3.cfg>.
However, this may change at any time.

**Comment by madaxel** [comment]
Hi @schams-net , thx.
What would be the correct way to keep the nagios cfg up to date? do you have scripts for your config or is there a way to query the TER?

**Comment by schams-net** [comment]
There are several ways: You can download the `check-typo3.cfg` file from the location listed above (I suggest not to trigger the download more than once a day).

Alternatively, you can maintain your own config file with your own definitions (e.g. add the TYPO3 versions and extensions you want Nagios to raise an alarm about).

Or you can install the extension [EXT:nagios_extensionlist](https://github.com/schams-net/nagios_extensionlist) and test if this meets your requirement. This extension generates a config file that contains insecure TYPO3 extensions based on the extension list of your TYPO3 instance (which is basically the data from the TER).

Another option is to download and parse the [extensions.xml](https://typo3.org/fileadmin/ter/extensions.xml.gz) file from the TER directly.
